apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "academy.name" . }}-mysql
  labels:
    app.kubernetes.io/name: {{ include "academy.name" . }}
    helm.sh/chart: {{ include "academy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "academy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "academy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.mysql.image.repository }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

{{- if .Values.globalEnvironments.enabled }}
        env:
{{ toYaml .Values.globalEnvironments.environments | indent 8 }}
{{- end }}
        ports:
          - name: http
            containerPort: 3306
            protocol: TCP

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http

{{- if .Values.imageSecret.enabled }}
      imagePullSecrets:
{{ toYaml .Values.imageSecret.allSecrets | indent 8 }}
{{- end }}

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
