apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-webplaform
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-fuchicorp-prod
spec:
  rules:
  - host: {{ .Values.dns_endpoint }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.webplatform_service }}
          servicePort: {{ .Values.webplatform_port }}

  - host: {{ .Values.api_endpoint }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.api_platform_service }}
          servicePort: {{ .Values.api_platform_port }}
  tls:
  - hosts:
    - {{ .Values.dns_endpoint }}
    - {{ .Values.api_endpoint }}
    secretName: letsencrypt-sec-webplatform-prod
