apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt-issuer-webplatform-prod
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: {{ .Values.email }}
   privateKeySecretRef:
     name: issuer-secret-webplatform
   http01: {}
