academy:
  build: .
  ports:
  - "5000:5000"
  volumes: 
  - ./:/app/
  - ~/.kube:/root/.kube/
  environment: 
   GIT_TOKEN: ${GIT_TOKEN}
   GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
   GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
   GOOGLE_APPLICATION_CREDENTIALS: /root/.kube/flask-kube.json
  command:
  - python
  - /app/app.py
  - --debug
