apiVersion: v1
kind: Pod
metadata:
  name: username
  labels:
    run: username
spec:
  containers:
  - name: username
    image: fsadykov/pynote:0.2
    args: ["--username=farkhodsadykov", "--password=redhat"]
  restartPolicy: OnFailure
