name: FuchiCorp Video configuration
items:

 - path: fuchicorp
   name: FuchiCorp Cluster Changes
   image: /static/images/videos/Python.jpg
   items:
     - name: Migrate from FuchiCorp Jenkins to official Jenkins
       uuid: '362457427'
       description:  In this session, we migrate from FuchiCorp Jenkins to official Jenkins
       url: https://player.vimeo.com/video/362457427
       status: True
       width: 640
       height: 564
       allow: "autoplay; fullscreen"
       role: students

     - name: FuchiCorp Helm deployment Artemis
       uuid: '362456906'
       description:  In this session, we talk about helm deployment and Kubernetes
       url: https://player.vimeo.com/video/362456906
       status: True
       width: 640
       height: 564
       allow: "autoplay; fullscreen"
       role: students


     - name: Common Script and Terraform Deployment
       uuid: '358836499'
       description:  We have created common script to set up environment for terraform
       url: https://player.vimeo.com/video/358836499
       status: True
       width: 640
       height: 564
       allow: "autoplay; fullscreen"
       role: students

 - path: pythonrecords
   name: Python class video records.
   image: /static/images/videos/Python.jpg
   items:
    - name: Python class 1 Data Types
      uuid: a32548f
      description:  In this class we covered only data types.
      url: https://player.vimeo.com/video/341489500
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

    - name: Python Class If statement
      uuid: 0bcee22
      description: In this class we conevered if statements.
      url: https://player.vimeo.com/video/342161116
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

    - name: Working with JSON and libraries
      uuid: 8bf9733
      description: In this class we covered Functions.
      url: https://player.vimeo.com/video/341489500
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

    - name: Python Class Application Programing Interface.
      uuid: a5832a
      description: Working with JSON data.
      url: https://player.vimeo.com/video/344231710
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

    - name: Boto3 First Class
      uuid: b41fc4
      description: Working with Boto3
      url: https://player.vimeo.com/video/348292662
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

    - name: Object Oriented Programming
      uuid: bd371a
      description: Object Oriented Programming
      url: https://player.vimeo.com/video/346996941
      status: True
      width: 640
      height: 564
      allow: "autoplay; fullscreen"
      role: students

 - path: python
   name: python short videos
   image: /static/images/videos/Python.jpg
   items:
     - name: Python class 1 Data Types
       uuid: a32548f
       description:  In this class we covered only data types.
       url: https://player.vimeo.com/video/341489500
       status: True
       width: 640
       height: 564
       allow: "autoplay; fullscreen"
       role: students

 - path: docker
   image: /static/images/videos/Docker.jpg
   name: Docker Classes
   items:
     - name: Docker introduction
       uuid: '1111'

 - path: ansible
   image: /static/images/videos/Ansible.jpg
   name: Ansible Classes
   items:
     - name: Ansible introduction
       uuid: '1111'

 - path: jenkins
   image: /static/images/videos/DevOps.jpg
   name: Jenkins Class
   items:
     - name: Jekins introduction
       uuid: '1111'

 - path: mysql
   image: /static/images/videos/MYSQL.jpg
   name: MySQL Class
   items:
     - name: Jekins introduction
       uuid: '1111'
